# Generated by Django 5.1.7 on 2025-04-13 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics_app', '0002_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='quantity_in_stock',
            field=models.IntegerField(default=0),
        ),
    ]
