# Generated by Django 5.1.7 on 2025-04-24 22:33

import logistics_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics_app', '0003_alter_item_quantity_in_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='tracking_number',
            field=models.CharField(default=logistics_app.models.generate_tracking_number, editable=False, help_text='Auto‑generated tracking code', max_length=20, unique=True),
        ),
    ]
